### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bsaund** [bsaund/TeamError404#2]
- [x] Learn Github
- [ ] Go to Kickoff
- [ ] Brainstorm Ideas for Robot
- [ ] Finalize Design
- [ ] Start Building Chasis
- [ ] Connect Electrical
- [ ] Add extra components
